version: '3.8'

services:
  app:
    build: .
    container_name: parking-management-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/parking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./logs:/var/log/parking-management
    networks:
      - parking-network
    restart: always

  postgres:
    image: postgres:14-alpine
    container_name: parking-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=parking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - parking-network
    restart: always

volumes:
  postgres-data:

networks:
  parking-network:
    driver: bridge